permissions:
  contents: read  
  
on:
  push:
    branches: [ "main" ,"test", "stagin"]
  workflow_dispatch:

jobs: 
  init:
    name: CI Workflow
    uses: codeparce/ci-workflows/.github/workflows/pipeline.node.cae.yml@v1
    with:
      cloud: azure
    secrets: inherit